const mockedBadges = [
  {
    _id: 3,
    name: 'Ajudante da Comunidade 3',
    description: 'Realizou dez ofertas no aplicativo',
    iconName: 'volunteer-activism',
    neededValue: 5,
    rank: 3,
    category: 'offer',
  },
  {
    _id: 2,
    name: 'Ajudante da Comunidade 2',
    description: 'Criou cinco ofertas no aplicativo',
    iconName: 'volunteer-activism',
    neededValue: 5,
    rank: 2,
    category: 'offer',
    nextBadge: 3,
  },
  {
    _id: 1,
    name: 'Ajudante da Comunidade 1',
    description: 'Criou uma oferta no aplicativo',
    iconName: 'volunteer-activism',
    neededValue: 1,
    rank: 1,
    category: 'offer',
    nextBadge: 2,
  },
  {
    _id: 6,
    name: 'Mudando Vidas 3',
    description: 'Finalizou dez ofertas no aplicativo',
    iconName: 'stars',
    neededValue: 5,
    rank: 3,
    category: 'help',
  },
  {
    _id: 5,
    name: 'Mudando Vidas 2',
    description: 'Finalizou cinco ofertas no aplicativo',
    iconName: 'stars',
    neededValue: 5,
    rank: 2,
    category: 'help',
    nextBadge: 6,
  },
  {
    _id: 4,
    name: 'Mudando Vidas 1',
    description: 'Criou uma oferta no aplicativo',
    iconName: 'stars',
    neededValue: 1,
    rank: 1,
    category: 'help',
    nextBadge: 5,
  },
];

module.exports = mockedBadges;
